CREATE TABLE mahasiswa (
	nim VARCHAR(11) NOT NULL PRIMARY KEY,
	nama VARCHAR(255) NOT NULL,
	alamat VARCHAR(255),
	fakultas VARCHAR(255)
)

INSERT INTO mahasiswa VALUES('H071211001','INDAH KURNIA ILAHI','Makassar', 'MIPA');
INSERT INTO mahasiswa VALUES('H071211003','SELVIANI AMALIA KARTIKA','Indonesia','MIPA');
INSERT INTO mahasiswa VALUES('H071211004','Muhammad Arif','Asia','MIPA');
